# -*- coding: utf-8 -*-
"""UploadToMongo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DsiBooKOvKW2SVnVyLqsQyfkYjbD-o6X
"""

import pandas as pd
from pymongo import MongoClient
import os
from google.colab import userdata

userdata.get('MONGODB_URI')
mongo_uri = "mongodb+srv://directoryAdmin:mFGaMJQqIGRvps7h@njproviderandtransit.bf50k.mongodb.net/NJProviderandTransit?retryWrites=true&w=majority"
client = MongoClient(mongo_uri)
database = client["NJProviderandTransit"]


csv_to_mongo = pd.read_csv("/content/drive/MyDrive/gecoded_filtered_bus_routes_converted.csv")

csv_to_mongo.fillna("Not Available", inplace=True)

for state_abbr, group in csv_to_mongo.groupby("state"):
  collection_name = f"{state_abbr}_transitcollection"
  collection = database[collection_name]
  data = group.to_dict(orient="records")

  collection.insert_many(data)
  print(f"Data inserted into {collection_name} successfully!")